export const TURNOS = [
  "TURNO MAÑANA",
  "TURNO TARDE",
  "TURNO NOCHE",
] as const;

export const SUPERVISORES = [
  "197 - Zalazar, Néstor",
  "94 - Bella, Eduardo",
  "140 - Akerman, Héctor",
  "372 - Obeid, Yair",
  "126 - Fernandez, Agustín",
  "6 - Silva, Darío",
] as const;

export const OPERARIOS = [
  "377 - Oneto, Sergio Emanuel",
  "162 - Benavento, Adrian Federico",
  "344 - Omar, Luis Hernán",
  "498 - Lucero Tolosa, Ruben Dario",
  "650 - Benavento, Darío",
  "399 - Beron, Ernesto Andrés",
  "409 - Pereyra, Enzo Diego",
  "550 - Villani, Daniel Adrián",
  "502 - Zapata, Juan Ignacio",
  "492 - Vera, Juan Gabriel",
  "294 - Lencina, Gastón Alejandro",
  "320 - Sosa, Daniel Eduardo",
  "234 - Machado, Abel Alejandro",
  "489 - Morales, Facundo Leonel",
  "526 - Barrios, Nicolas Alejandro",
  "714 - Torres, Víctor",
  "407 - Zapata, Federico Damián",
  "128 - Zapata, Martin Daniel",
  "555 - Figueras, Rodrigo",
  "65 - Enrique, Juan Carlos",
  "469 - Wagner, Cristian Román",
  "328 - Seghesso, Luis Darío",
  "141 - Velazquez, Leonardo Ramón",
  "643 - Buchardo, Cristian",
  "696 - Páez, Carlos",
  "313 - Juarez, Walter Alberto",
  "593 - Atencio, Brian Franco",
  "504 - Machado, Carlos Angel E",
  "401 - Taborda, Ernesto Rubén",
  "169 - Garcia, Ramón Ariel",
  "694 - Gimenez, Luciano",
  "252 - Beron, Roberto Marcelo",
  "219 - Flores, Christian",
  "429 - Magistrelli, Carlos Javier",
  "707 - Reitú, Axel",
  "453 - Flores, Sabino Andrés",
  "124 - Lencina, Héctor Ramón",
  "321 - Vallejos, Carlos",
  "173 - Enrique, José Luis",
  "137 - Bejariel, Rubén",
  "198 - Medrano, Pedro Alberto",
  "546 - Peralta, Gustavo Andrés",
  "528 - Akerman, Martin Sebastian",
  "386 - Guzman, Ramiro Daniel",
  "220 - Zapata, Víctor Marcelo",
  "524 - Morales, Guillermo Pablo",
  "165 - Brasesco, Mauricio Rodolfo",
  "110 - Ramirez, Abel Gregorio",
  "499 - Coronel, Emmanuel",
  "86 - Capelari, Gastón Roberto",
  "460 - Charpentier, Maximiliano",
  "661 - Poletti, Paulo",
  "712 - Ruiz Moreno, Julian",
  "586 - Beltaco, Matías",
  "304 - Godoy, Cristian Alberto",
  "118 - Brassesco, Javier Evaristo",
  "380 - Benitez, Edgar",
  "362 - Loza, Ariel David",
  "587 - Díaz, Claudio Daniel",
  "466 - Lallana, Alfredo Euclides",
  "385 - Aguirre, Claudio Fabián",
  "710 - Montojo, Leonel",
  "214 - Navoni, Ramón Agustín",
  "494 - Acosta, Franco Marcelo",
  "553 - Alvarez, Joaquín Ignacio",
  "163 - Rueda, Franco Emiliano",
  "554 - Saldaña, Leonel",
  "507 - Alaguibe, Lucas Mauricio",
  "450 - Godoy, Franco David",
  "496 - Tillar Torigino, Aldo Carmelo",
  "655 - Vigliani Santiago",
  "709 - Robledo, Juan Manuel",
  "708 - Héctor Leones",
  "540 - Machado, Augusto",
  "391 - Zapata, Francisco Daniel",
  "205 - Riquelme Santiago",
  "334 - Beron, Raúl Gustavo",
  "311 - Hernandez, Manuel",
] as const;

export const OBJETIVO_MOLDES_COLADOS = 19;
export const OBJETIVO_RENDIMIENTO_HORA = 50; // CM/hora

export const MOTIVOS_AUSENCIA = [
  "AI - AUSENCIA INJUSTIFICADA",
  "ASA - AUSENTE SIN AVISO",
  "AV - ADELANTO DE VACACIONES",
  "CAP - OPERARIO EN CAPACITACIÓN",
  "DC - DEVOLUCIÓN POR CAMBIO DE DÍA",
  "LAL - LICENCIA ACCIDENTE LABORAL",
  "LDS - LICENCIA DONACIÓN DE SANGRE",
  "LE - LICENCIA PARA EXAMEN",
  "LFF - LICENCIA POR FALLECIMIENTO DE FAMILIAR",
  "LM - LICENCIA MEDICA",
  "LMA - LICENCIA POR MATRIMONIO",
  "LME - LICENCIA POR MATERNIDAD ESTADO DE EXEDENCIA",
  "LMM - LICENCIA POR MATERNIDAD",
  "LN - LICENCIA POR NACIMIENTO",
  "PPC - PROCEDIMIENTO PREVENTIVO DE CRISIS",
  "RP - RESERVA DE PUESTO",
  "SD - SUSPENCIÓN DISCIPLINARIA",
  "AUSENTE CON AVISO",
] as const;

export const PUESTOS = [
  "Acondicionamiento",
  "Autoelevador",
  "Caldera",
  "Corte - Auxiliar",
  "Corte - Titular",
  "Curado",
  "Desmantelado",
  "Desmolde - Maquinista",
  "Desmolde - Paletizador",
  "Empaquetador",
  "Jefatura/ Administración",
  "Laboratorio",
  "Limpieza",
  "Maduración - Armador",
  "Maduración - Operario",
  "Maestranza",
  "Mantenimiento",
  "Molino",
  "Pañol",
  "Portería",
  "Rotador",
  "Sala de control",
  "Supervisor",
  "Transformación",
] as const;

export const AGUA_EN_USO = [
  "Condensado",
  "Semisurgente",
  "Condensado/Semisurgente",
  "Semisurgente/Condensado",
] as const;

export const SISTEMA_DOSIFICACION = ["Manual", "Automático"] as const;

export const CALOVENTORES_MODO = ["Automático", "Manual"] as const;

export type TabDef = {
  id: string;
  label: string;
  sectionKey: string;
};

export const TABS: TabDef[] = [
  { id: "encabezado", label: "Encabezado", sectionKey: "encabezado" },
  { id: "general", label: "General", sectionKey: "general" },
  { id: "personal", label: "Personal", sectionKey: "personal" },
  { id: "molino3", label: "Molino 3", sectionKey: "molino3" },
  { id: "stockBarro", label: "Stock Barro", sectionKey: "stockBarro" },
  { id: "salaControl", label: "Sala de Colado", sectionKey: "salaControl" },
  { id: "maduracion", label: "Maduración", sectionKey: "maduracion" },
  { id: "corte", label: "Corte", sectionKey: "corteDesmantelado" },
  { id: "rotador", label: "Rotador", sectionKey: "rotador" },
  { id: "precurado", label: "Precurado", sectionKey: "precuradoAutoclaves" },
  { id: "caldera", label: "Caldera", sectionKey: "caldera" },
  { id: "desmolde", label: "Desmolde", sectionKey: "desmolde" },
  { id: "granallado", label: "Granallado", sectionKey: "granallado" },
  { id: "scrap", label: "Scrap", sectionKey: "scrap" },
  { id: "transformacion", label: "Transformación", sectionKey: "transformacion" },
  { id: "autoelevadores", label: "Autoelevadores", sectionKey: "autoelevadores" },
];
