
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
// Load .env first, then .env.development.local overrides (mirrors Next.js behavior)
dotenv.config({ path: ".env" });
dotenv.config({ path: ".env.development.local", override: true });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
