import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

const SETTINGS = [
  {
    key: "turnos",
    value: ["TURNO MAÑANA", "TURNO TARDE", "TURNO NOCHE"],
    label: "Turnos",
    description: "Lista de turnos disponibles",
  },
  {
    key: "supervisores",
    value: [
      "197 - Zalazar, Néstor",
      "94 - Bella, Eduardo",
      "140 - Akerman, Héctor",
      "372 - Obeid, Yair",
      "126 - Fernandez, Agustín",
      "6 - Silva, Darío",
    ],
    label: "Supervisores",
    description: "Lista de supervisores habilitados",
  },
  {
    key: "operarios",
    value: [
      "377 - Oneto, Sergio Emanuel",
      "162 - Benavento, Adrian Federico",
      "344 - Omar, Luis Hernán",
      "498 - Lucero Tolosa, Ruben Dario",
      "650 - Benavento, Darío",
      "399 - Beron, Ernesto Andrés",
      "409 - Pereyra, Enzo Diego",
      "550 - Villani, Daniel Adrián",
      "502 - Zapata, Juan Ignacio",
      "492 - Vera, Juan Gabriel",
      "294 - Lencina, Gastón Alejandro",
      "320 - Sosa, Daniel Eduardo",
      "234 - Machado, Abel Alejandro",
      "489 - Morales, Facundo Leonel",
      "526 - Barrios, Nicolas Alejandro",
      "714 - Torres, Víctor",
      "407 - Zapata, Federico Damián",
      "128 - Zapata, Martin Daniel",
      "555 - Figueras, Rodrigo",
      "65 - Enrique, Juan Carlos",
      "469 - Wagner, Cristian Román",
      "328 - Seghesso, Luis Darío",
      "141 - Velazquez, Leonardo Ramón",
      "643 - Buchardo, Cristian",
      "696 - Páez, Carlos",
      "313 - Juarez, Walter Alberto",
      "593 - Atencio, Brian Franco",
      "504 - Machado, Carlos Angel E",
      "401 - Taborda, Ernesto Rubén",
      "169 - Garcia, Ramón Ariel",
      "694 - Gimenez, Luciano",
      "252 - Beron, Roberto Marcelo",
      "219 - Flores, Christian",
      "429 - Magistrelli, Carlos Javier",
      "707 - Reitú, Axel",
      "453 - Flores, Sabino Andrés",
      "124 - Lencina, Héctor Ramón",
      "321 - Vallejos, Carlos",
      "173 - Enrique, José Luis",
      "137 - Bejariel, Rubén",
      "198 - Medrano, Pedro Alberto",
      "546 - Peralta, Gustavo Andrés",
      "528 - Akerman, Martin Sebastian",
      "386 - Guzman, Ramiro Daniel",
      "220 - Zapata, Víctor Marcelo",
      "524 - Morales, Guillermo Pablo",
      "165 - Brasesco, Mauricio Rodolfo",
      "110 - Ramirez, Abel Gregorio",
      "499 - Coronel, Emmanuel",
      "86 - Capelari, Gastón Roberto",
      "460 - Charpentier, Maximiliano",
      "661 - Poletti, Paulo",
      "712 - Ruiz Moreno, Julian",
      "586 - Beltaco, Matías",
      "304 - Godoy, Cristian Alberto",
      "118 - Brassesco, Javier Evaristo",
      "380 - Benitez, Edgar",
      "362 - Loza, Ariel David",
      "587 - Díaz, Claudio Daniel",
      "466 - Lallana, Alfredo Euclides",
      "385 - Aguirre, Claudio Fabián",
      "710 - Montojo, Leonel",
      "214 - Navoni, Ramón Agustín",
      "494 - Acosta, Franco Marcelo",
      "553 - Alvarez, Joaquín Ignacio",
      "163 - Rueda, Franco Emiliano",
      "554 - Saldaña, Leonel",
      "507 - Alaguibe, Lucas Mauricio",
      "450 - Godoy, Franco David",
      "496 - Tillar Torigino, Aldo Carmelo",
      "655 - Vigliani Santiago",
      "709 - Robledo, Juan Manuel",
      "708 - Héctor Leones",
      "540 - Machado, Augusto",
      "391 - Zapata, Francisco Daniel",
      "205 - Riquelme Santiago",
      "334 - Beron, Raúl Gustavo",
      "311 - Hernandez, Manuel",
    ],
    label: "Operarios / Autoelevadoristas",
    description: "Lista de operarios para autoelevadores y otros usos",
  },
  {
    key: "motivos_ausencia",
    value: [
      "AI - AUSENCIA INJUSTIFICADA",
      "ASA - AUSENTE SIN AVISO",
      "AV - ADELANTO DE VACACIONES",
      "CAP - OPERARIO EN CAPACITACIÓN",
      "DC - DEVOLUCIÓN POR CAMBIO DE DÍA",
      "LAL - LICENCIA ACCIDENTE LABORAL",
      "LDS - LICENCIA DONACIÓN DE SANGRE",
      "LE - LICENCIA PARA EXAMEN",
      "LFF - LICENCIA POR FALLECIMIENTO DE FAMILIAR",
      "LM - LICENCIA MEDICA",
      "LMA - LICENCIA POR MATRIMONIO",
      "LME - LICENCIA POR MATERNIDAD ESTADO DE EXEDENCIA",
      "LMM - LICENCIA POR MATERNIDAD",
      "LN - LICENCIA POR NACIMIENTO",
      "PPC - PROCEDIMIENTO PREVENTIVO DE CRISIS",
      "RP - RESERVA DE PUESTO",
      "SD - SUSPENCIÓN DISCIPLINARIA",
      "AUSENTE CON AVISO",
    ],
    label: "Motivos de ausencia",
    description: "Códigos de motivos de ausencia del personal",
  },
  {
    key: "puestos",
    value: [
      "Acondicionamiento",
      "Autoelevador",
      "Caldera",
      "Corte - Auxiliar",
      "Corte - Titular",
      "Curado",
      "Desmantelado",
      "Desmolde - Maquinista",
      "Desmolde - Paletizador",
      "Empaquetador",
      "Jefatura/ Administración",
      "Laboratorio",
      "Limpieza",
      "Maduración - Armador",
      "Maduración - Operario",
      "Maestranza",
      "Mantenimiento",
      "Molino",
      "Pañol",
      "Portería",
      "Rotador",
      "Sala de control",
      "Supervisor",
      "Transformación",
    ],
    label: "Puestos de trabajo",
    description: "Lista de puestos disponibles para cambios de puesto",
  },
  {
    key: "objetivo_moldes_colados",
    value: 19,
    label: "Objetivo moldes colados / turno",
    description: "Meta de moldes colados por turno",
  },
  {
    key: "objetivo_rendimiento_hora",
    value: 50,
    label: "Objetivo rendimiento (CM/hora)",
    description: "Meta de rendimiento del molino en CM/hora",
  },
  {
    key: "email_to",
    value: "matiasr@ardal.com.ar",
    label: "Email destinatario FDT",
    description: "Dirección a la que se envían los reportes de fin de turno",
  },
];

async function main() {
  console.log("Seeding settings...");
  for (const s of SETTINGS) {
    await prisma.setting.upsert({
      where: { key: s.key },
      create: s,
      update: { value: s.value, label: s.label, description: s.description },
    });
    console.log(`  ✓ ${s.key}`);
  }
  console.log("Done.");
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
